[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs         # Temporary directory for egg installations
  | \.git        # Git version control directory
  | \.hg         # Mercurial version control directory
  | \.mypy_cache # MyPy cache directory
  | \.tox        # Tox testing tool directory
  | \.venv       # Virtual environment directory
  | build        # Build output directory
  | dist         # Distribution output directory
)/
'''

[tool.isort]
profile = "black"  # Use Black-compatible defaults
multi_line_output = 3  # Vertical Hanging Indent
include_trailing_comma = true  # Include a trailing comma on multi-line imports
force_grid_wrap = 0  # Don't force grid wrapping
use_parentheses = true  # Use parentheses for line continuation
ensure_newline_before_comments = true  # Ensure new line before comments
line_length = 88  # Should match Black's line length

[tool.mypy]
python_version = "3.11"
disallow_untyped_defs = false
ignore_missing_imports = true
show_error_codes = true
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
check_untyped_defs = true
no_implicit_optional = true
warn_unused_configs = true

[tool.ruff]
line-length = 88

# Exclude directories
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    "venv",
]

# Similar to Flake8's ignore list
ignore = [
    "E203",  # Whitespace before ':'
    "E266",  # Too many leading '#' for block comment
    "E501",  # Line too long (handled by line-length)
    "F405",  # Unused import
]

# Allow unused imports in __init__.py files
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

# Maximum McCabe complexity
[tool.ruff.mccabe]
max-complexity = 10